import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import StoreProvider from "@/providers/StoreProvider";
import MobileNavbar from "@/components/MobileNavbar";

export const metadata: Metadata = {
  title: "Budget Tracker App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex overflow-hidden ">
        <StoreProvider>
          <div className="flex-[1] hidden md:flex">
            <Sidebar />
          </div>
          <div className="flex-[5] w-full h-screen overflow-y-auto bg-slate-900 text-white  ">
            <div className="md:hidden">
              <MobileNavbar />
            </div>
            {children}
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
